### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by alexwilson** [antoligy/Terminator#1]
#### Todo
- [ ] Clean-up code.
- [ ] Add tests.
- [ ] Automatic (cross-platform) builds.
- [ ] Write some documentation.
- [x] Parallelise as this will choke with large datasets.
